import type {Config,Service} from './faultline-types';
const s=(id:string,name:string,kind:Service['kind'],latency:number,capacity:number,dependencies:string[]=[]):Service=>({id,name,kind,latency,capacity,dependencies,errorRate:0});
export const presets:{id:string;config:Config}[]=[
{id:'storefront',config:{version:1,name:'Storefront API',seed:2048,entry:'gateway',rps:80,duration:45,services:[s('gateway','API Gateway','gateway',12,100,['auth','checkout']),s('auth','Auth Service','service',18,80,['redis']),s('checkout','Checkout','service',35,50,['payments','postgres']),s('redis','Redis Cache','cache',4,100),s('payments','Payments API','external',90,40),s('postgres','PostgreSQL','database',22,35)],policy:{timeout:700,retries:1,backoff:100,jitter:true,circuitBreaker:false},fault:{enabled:true,target:'postgres',type:'latency',value:900,start:12,duration:20}}},
{id:'inference',config:{version:1,name:'AI inference pipeline',seed:2048,entry:'gateway',rps:30,duration:45,services:[s('gateway','API Gateway','gateway',15,100,['orchestrator']),s('orchestrator','AI Orchestrator','service',30,60,['llm','retrieval','moderation']),s('llm','Model Provider','external',450,40),s('retrieval','Vector Search','database',45,60),s('moderation','Moderation','service',70,80)],policy:{timeout:1800,retries:1,backoff:200,jitter:true,circuitBreaker:false},fault:{enabled:true,target:'llm',type:'errors',value:65,start:10,duration:20}}},
{id:'saas',config:{version:1,name:'SaaS backend',seed:1024,entry:'gateway',rps:70,duration:45,services:[s('gateway','API Gateway','gateway',10,100,['workspace','identity']),s('workspace','Workspace API','service',25,60,['database','identity']),s('identity','Identity Service','service',20,45,['cache']),s('database','Primary Database','database',30,50),s('cache','Session Cache','cache',5,80)],policy:{timeout:600,retries:2,backoff:100,jitter:false,circuitBreaker:false},fault:{enabled:true,target:'identity',type:'outage',value:100,start:10,duration:20}}}
];
export const ms=(n:number)=>n>=1000?`${(n/1000).toFixed(2)} s`:`${Math.round(n)} ms`;
export const num=(n:number)=>new Intl.NumberFormat('en-US').format(n);
export const faultNames={latency:'Latency spike',errors:'Error burst',outage:'Service outage',capacity:'Capacity squeeze'};
