'use client';
import{Database,Server,Network,HardDrive,ShieldCheck,CreditCard,Cpu,Zap}from'lucide-react';
import type{Config,Simulation,Service,Result}from'@/lib/faultline-types';
import{ms}from'@/lib/presets';
import{useState}from'react';
export function ServiceIcon({service,size=18}:{service:Service;size?:number}){const I=service.kind==='database'?Database:service.kind==='cache'?HardDrive:service.kind==='gateway'?Network:service.id==='auth'||service.id==='identity'?ShieldCheck:service.id==='payments'?CreditCard:service.id==='llm'||service.id==='orchestrator'?Cpu:Server;return <I size={size} strokeWidth={1.6}/>;}
export function Graph({config,result,onSelect,running}:{config:Config;result?:Simulation;onSelect:(id:string)=>void;running:boolean}){
 const depth:Record<string,number>={};const walk=(id:string,d:number)=>{if(d>12||(depth[id]!==undefined&&depth[id]>=d))return;depth[id]=d;config.services.find(s=>s.id===id)?.dependencies.forEach(c=>walk(c,d+1));};walk(config.entry,0);
 const max=Math.max(...Object.values(depth)),width=Math.max(790,(max+1)*230),rows=Math.max(...Array.from({length:max+1},(_,i)=>config.services.filter(s=>depth[s.id]===i).length)),height=Math.max(350,rows*102+40),pos:Record<string,{x:number;y:number}>={};
 for(let d=0;d<=max;d++){const nodes=config.services.filter(s=>depth[s.id]===d);nodes.forEach((s,i)=>pos[s.id]={x:max?35+d*(width-245)/max:width/2-86,y:(i+.5)*(height-30)/nodes.length+15-37});}
 return <div className={`graph-scroll ${running?'running':''}`}><svg style={{minWidth:width}} viewBox={`0 0 ${width} ${height}`} role="group" aria-label="Editable service dependency graph"><defs><pattern id="dots" width="18" height="18" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="#29333b"/></pattern><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L6 3.5L0 7" fill="none" stroke="#51745f"/></marker></defs><rect width="100%" height="100%" fill="url(#dots)"/>
 {config.services.flatMap(s=>s.dependencies.map(id=>{const a=pos[s.id],b=pos[id];if(!a||!b)return null;const x=a.x+174,y=a.y+37,ex=b.x-3,ey=b.y+37,d=`M${x},${y} C${(x+ex)/2},${y} ${(x+ex)/2},${ey} ${ex},${ey}`;return <g key={`${s.id}-${id}`}><path d={d} className={`edge ${config.fault.enabled&&id===config.fault.target?'fault-edge':''}`} markerEnd="url(#arrow)"/><path d={d} className="flow"/></g>;}))}
 {config.services.map(s=>{const p=pos[s.id],target=config.fault.enabled&&config.fault.target===s.id,stat=result?.services[s.id];if(!p)return null;return <g key={s.id} transform={`translate(${p.x},${p.y})`} role="button" tabIndex={0} aria-label={`Configure ${s.name}`} onClick={()=>onSelect(s.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(s.id);}}} className={`node ${target?'target':stat&&stat.errorRate>1?'impacted':''}`}>
 {target&&<rect x="-4" y="-4" width="182" height="82" rx="13" className="halo"/>}<rect width="174" height="74" rx="9" className="node-bg"/><rect x="12" y="12" width="29" height="29" rx="7" className="icon-bg"/><g transform="translate(18,18)" className="node-icon"><ServiceIcon service={s} size={17}/></g><text x="51" y="26" className="node-name">{s.name.length>17?s.name.slice(0,16)+'…':s.name}</text><text x="51" y="44" className="node-kind">{s.kind==='external'?'external API':s.kind}</text><circle cx="17" cy="59" r="2.5" fill={target?'#e9b969':stat&&stat.errorRate>1?'#ed9787':'#67c6a1'}/><text x="25" y="63" className="node-stat">{stat?`${ms(stat.p95)} p95`:`${s.latency} ms base`}</text><text x="160" y="63" textAnchor="end" className="node-stat">{stat?`${Math.round(stat.errorRate)}% err`:`${s.capacity} slots`}</text>{target&&<g transform="translate(139,-11)"><rect x="-1" y="-3" width="25" height="22" rx="6" fill="#e9b969"/><Zap x="5" y="1" width="14" height="14" fill="#1c1a14" stroke="#1c1a14"/></g>}</g>;})}</svg></div>;
}
export function LatencyChart({result}:{result:Result}){
 const[hover,setHover]=useState<number|null>(null);const data=result.experiment.series,base=result.baseline.series,max=Math.max(100,...data.map(s=>s.p95),...base.map(s=>s.p95))*1.12,x=(i:number)=>58+i/Math.max(1,data.length-1)*822,y=(n:number)=>144-n/max*129,path=(a:typeof data)=>a.map((p,i)=>`${i?'L':'M'}${x(p.second)},${y(p.p95)}`).join(' '),f=result.config.fault,begin=Math.min(data.length-1,f.start),end=Math.min(data.length-1,f.start+f.duration),selected=hover===null?null:data[hover];
 return <div className="chart" onMouseLeave={()=>setHover(null)}><svg viewBox="0 0 900 174" role="img" aria-label="P95 response time by request arrival second" onMouseMove={e=>{const b=e.currentTarget.getBoundingClientRect(),v=(e.clientX-b.left)/b.width*900;setHover(Math.max(0,Math.min(data.length-1,Math.round((v-58)/822*(data.length-1)))));}}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c4ef84" stopOpacity=".17"/><stop offset="100%" stopColor="#c4ef84" stopOpacity="0"/></linearGradient></defs>{[0,.5,1].map(v=><g key={v}><line x1="58" x2="880" y1={y(max*v)} y2={y(max*v)} className="gridline"/><text x="46" y={y(max*v)+4} textAnchor="end" className="chart-label">{max*v>=1000?`${(max*v/1000).toFixed(1)}s`:`${Math.round(max*v)}ms`}</text></g>)}{f.enabled&&end>begin&&<><rect x={x(begin)} y="15" width={x(end)-x(begin)} height="129" fill="#e9b969" opacity=".055"/><line x1={x(begin)} x2={x(begin)} y1="15" y2="144" stroke="#a58a54" strokeDasharray="3 4"/><text x={x(begin)+7} y="29" className="chart-label">fault window</text></>}
 <path d={`${path(data)} L${x(data.length-1)},144 L58,144 Z`} fill="url(#fill)"/><path d={path(base)} fill="none" stroke="#68778b" strokeWidth="1.5" strokeDasharray="4 4"/><path d={path(data)} fill="none" stroke="#c4ef84" strokeWidth="2" strokeLinejoin="round"/>{[0,.25,.5,.75,1].map(v=>{const i=Math.round((data.length-1)*v);return <text key={v} x={x(i)} y="168" textAnchor="middle" className="chart-label">{i}s</text>;})}{selected&&<><line x1={x(selected.second)} x2={x(selected.second)} y1="15" y2="144" stroke="#708070"/><circle cx={x(selected.second)} cy={y(selected.p95)} r="4" fill="#c4ef84"/></>}</svg>{selected&&<div className="chart-readout">{selected.second}s <strong>{ms(selected.p95)}</strong> {selected.successRate}% success</div>}</div>;
}
